export const mindStatusToYouTubeKeywords: Record<string, string[]> = {
  Focused: [
    "best motivational videos",
    "best productivity tips",
    "best motivational speeches",
    "how to become passionate about work",
    "how to improve focus",
    "how to increase productivity",
    "how to maintain health to stay focused",
    "how to achieve deep work",
    "how to enhance concentration",
    "how to avoid distractions",
    "how to stay in the zone",
    "how to boost mental clarity",
  ],
  Distracted: [
    "best ways to overcome distractions",
    "how to stay focused",
    "how to improve concentration",
    "how to avoid distractions",
    "how to regain focus",
    "how to manage distractions",
  ],
  Tired: [
    "best ways to overcome fatigue",
    "how to overcome fatigue",
    "how to boost energy",
    "how to recharge your mind",
    "how to rest effectively",
    "how to improve sleep quality",
    "how to manage tiredness",
    "how to increase productivity when tired",
  ],
  Stressed: [
    "best stress relief techniques",
    "how to manage stress",
    "how to reduce anxiety",
    "how to relax and unwind",
    "how to cope with stress",
    "how to practice mindfulness",
    "how to find inner peace",
    "how to deal with overwhelming feelings",
    "how to handle stress at work",
    "how to relieve stress quickly",
    "how to calm your mind",
    "how to practice self-care",
    "how to improve mental health",
  ],
  Motivated: [
    "best motivational videos",
    "how to stay motivated",
    "how to increase productivity",
    "how to set and achieve goals",
    "how to maintain motivation",
    "how to build positive habits",
    "how to find inspiration",
    "how to overcome procrastination",
  ],
  Default: [
    "best motivational videos",
    "how to improve focus",
    "how to increase productivity",
    "how to maintain health to stay focused",
    "how to achieve deep work",
    "how to enhance concentration",
    "how to avoid distractions",
    "how to stay in the zone",
    "how to boost mental clarity",
    "how to manage stress",
    "how to reduce anxiety",
    "how to relax and unwind",
    "how to cope with stress",
    "how to take care of mental health",
  ],
};


export const getSuggestedYoutubeKeywords = (mindStatus: string):string[] => {
  return mindStatusToYouTubeKeywords[mindStatus] || mindStatusToYouTubeKeywords["Default"];
}