export const mindStatusToYouTubeKeywords: Record<string, string[]> = {
  Focused: [
    "deep work motivation short",
    "focus short video",
    "productivity short",
    "no distractions short",
    "study focus motivation short",
    "how to concentrate short",
    "pomodoro technique short",
    "flow state explained short",
  ],
  Distracted: [
    "dopamine detox short",
    "regain focus short",
    "how to avoid distractions short",
    "mindfulness reminder short",
    "why you can't focus short",
    "stay focused motivation short",
    "short attention span fix short",
    "rewire brain short video",
  ],
  Tired: [
    "rest and recharge short",
    "sleep better tips short",
    "relaxing music short",
    "short calming video",
    "how to unwind short",
    "quick nap idea short",
    "low energy fix short",
    "bedtime affirmation short",
  ],
  Stressed: [
    "breathe with me short",
    "stress relief short",
    "meditation 1 minute short",
    "panic attack help short",
    "calm down quick short",
    "grounding technique short",
    "soothing visual short",
    "short anxiety relief video",
  ],
  Motivated: [
    "keep going short motivation",
    "short success story video",
    "motivational reel under 60s",
    "goal setter mindset short",
    "you are strong short",
    "push yourself short",
    "winners never quit short",
    "discipline motivation short",
  ],
  Default: [
    "daily inspirational short",
    "morning motivation short",
    "short quotes video",
    "life advice short",
    "uplifting words short",
    "short mental health tip",
    "positive mindset short",
    "simple joy video short",
  ],
};
